# Generated by Django 4.2.1 on 2023-06-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_post", models.CharField(max_length=10000000)),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
                ("user_name", models.CharField(max_length=40)),
                ("content", models.TextField()),
            ],
        ),
    ]
